name: code-chekout-linting 

on:
  workflow_dispatch:

jobs:
  code-checkout:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm install

      - name: Run Linter
        run: npm run lint

    